// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Persistence.Models;

public partial class Images
{
    public long Id { get; set; }

    public Guid Guid { get; set; }

    public string Url { get; set; } = null!;

    public int Resolution { get; set; }

    public long ImageGroupId { get; set; }

    public long CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public long? ModifiedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public virtual ImageGroups IdNavigation { get; set; } = null!;
}